# Generated by Django 3.2 on 2025-05-08 00:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], help_text='Estado da Conversa', max_length=20, verbose_name='Estado da Conversa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='data de criação', verbose_name='criado em')),
                ('finish_at', models.DateTimeField(blank=True, help_text='data de finalização', null=True, verbose_name='finalizado em')),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Conteudo da Mensagem', max_length=1000, verbose_name='Conteudo')),
                ('state', models.CharField(choices=[('SENT', 'Enviado'), ('RECEIVED', 'Recebido')], help_text='Estado da Mensagem', max_length=20, verbose_name='Estado da Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='data de criação', verbose_name='criado em')),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
    ]
