# Generated by Django 3.2 on 2025-05-08 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='conversation',
        #     name='id',
        # ),
        # migrations.RemoveField(
        #     model_name='message',
        #     name='id',
        # ),
        # migrations.AddField(
        #     model_name='message',
        #     name='conversation',
        #     field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.conversation', verbose_name='Conversa'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='conversation',
        #     name='slug',
        #     field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        # ),
        # migrations.AlterField(
        #     model_name='message',
        #     name='slug',
        #     field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        # ),
    ]
