# Generated by Django 4.2.21 on 2025-05-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250507_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='slug',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='slug',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(help_text='data de criação', verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(help_text='data de criação', verbose_name='criado em'),
        ),
    ]
