# Generated by Django 4.2.21 on 2025-05-08 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_slug_conversation_id_rename_slug_message_id_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='conversation',
        #     name='id',
        #     field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        # ),
        # migrations.AlterField(
        #     model_name='message',
        #     name='id',
        #     field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        # ),
    ]
