# Generated by Django 4.2.21 on 2025-05-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='FailedWebhookEvent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('type', models.CharField(max_length=50)),
        #         ('data', models.JSONField()),
        #         ('timestamp', models.DateTimeField()),
        #         ('error_message', models.TextField()),
        #         ('retry_count', models.IntegerField(default=0)),
        #         ('last_retry_at', models.DateTimeField(blank=True, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        # ),
    ]
