# Generated by Django 4.2.21 on 2025-05-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_failedwebhookevent_options_leadinformantion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadinformantion',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_info', to='api.conversation', verbose_name='Conversa'),
        ),
    ]
