# Generated by Django 4.2.21 on 2025-05-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_failedwebhookevent_options_leadinformantion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_property', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('price_track', models.CharField(blank=True, max_length=100, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('urgency', models.CharField(blank=True, max_length=50, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conversation', verbose_name='Conversa')),
            ],
            options={
                'verbose_name': 'Informações de imovel',
                'verbose_name_plural': 'Informações de imoveis',
            },
        ),
    ]
