# Generated by Django 4.2.21 on 2025-05-10 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_leadinformantion_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadinformantion',
            name='conversation',
        ),
        migrations.AddField(
            model_name='leadinformantion',
            name='conversation_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lead_info', to='api.conversation', verbose_name='Conversation'),
            preserve_default=False,
        ),
    ]
