# Generated by Django 4.2.21 on 2025-05-10 05:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_leadinfos'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='FailedWebhookEvent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('type', models.CharField(max_length=50)),
        #         ('data', models.JSONField()),
        #         ('timestamp', models.DateTimeField()),
        #         ('error_message', models.TextField()),
        #         ('retry_count', models.IntegerField(default=0)),
        #         ('last_retry_at', models.DateTimeField(blank=True, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #     ],
        #     options={
        #         'verbose_name': 'Evento do Webhook com Falha',
        #         'verbose_name_plural': 'Eventos do Webhook com Falha',
        #     },
        # ),
        migrations.RemoveField(
            model_name='conversation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.conversation', verbose_name='Conversa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(help_text='data de criação', verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(help_text='data de criação', verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
