# Generated by Django 4.2.21 on 2025-05-10 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_leadinformantion_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='leadinformantion',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='leadinformantion',
            name='conversation_slug',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lead_info', to='api.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=150, primary_key=True, serialize=False, unique=True, verbose_name='Slug'),
        ),
    ]
