# Generated by Django 4.2.21 on 2025-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_failedwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_property', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('price_track', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
    ]
